src/customers/urls.py
from django.urls import path

from customers.views import ProfileView, ProfileUpdatePasswordView, EditProfileView

app_name = 'customers'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', EditProfileView.as_view(), name='profile_update'),
    path('profile/change-password/', ProfileUpdatePasswordView.as_view(), name='profile_password_update'),
]

src/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('add-product/', views.AddProductView.as_view(), name='add_product'),
    path('upate-orderitem/', views.UpdateOrderItemView.as_view(), name='update_orderitem'),
    path('order-detail/<int:pk>/',  views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),

]

src/products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('register/', views.ProductCreateView.as_view(), name='product_create'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('<slug:slug>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('<slug:slug>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
]

src/users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/walkthisway/urls.py
from django.contrib import admin
from django.urls import path, include
from walkthisway.views import Index
from orders.views import my_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('', include('users.urls',namespace='users')),
    path('', include('customers.urls', namespace='customers')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('stripe/webhook/', my_webhook, name='stripe_webhook')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Isaias Alvarez Vargas">
    <meta name="description" content="Walk This Way is one of the hotest sites to buy your shoes!">
    <meta name="keywords" content="Shoes, Walk, This, Way, Sneakers">
    <title>Walk This Way</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/bd43079ab2.js" crossorigin="anonymous"></script>

    <script>
        user = '{{ request.user }}'

        function getCookie(name){
            // Split cookie string and get all individual name=value pairs
            var cookies = document.cookie.split(';');

            // Loop through array
            for(let i = 0; i < cookies.length; i++){
                let cookiePair = cookies[i].split('=');

                // Remove whitespace at the beginning of the name
                // and compare it with given string
                if (name == cookiePair[0].trim()){
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null;
        }

        let cart = JSON.parse(getCookie('cart'));
        if(!cart){
            cart = {};
            document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/';
        }
    </script>
</head>
<body>
    
    <header class="mb-5">
        {% include 'navbar.html' %}
    </header>


    <main>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </main>


    <footer>

    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h3 class="text-center">Walk in Style, <strong>Walk This Way</strong></h3>
{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">Walk This Way</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          <a class="nav-link" href="{% url 'products:product_list' %}">Products</a>
          <a class="nav-link" href="{% url 'orders:cart' %}">Cart</a>
          <a class="nav-link" href="{% url 'customers:profile' %}">Profile</a>
        </div>

        <div class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
          {% else %}
            <a href="{% url 'users:login' %}" class="nav-link">Log In</a>
            <a href="{% url 'users:register' %}" class="nav-link">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>