src/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('add-product/', views.AddProductView.as_view(), name='add_product'),
    path('upate-orderitem/', views.UpdateOrderItemView.as_view(), name='update_orderitem'),
    path('order-detail/<int:pk>/',  views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),

]

src/products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('register/', views.ProductCreateView.as_view(), name='product_create'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('<slug:slug>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('<slug:slug>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
]

src/users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/walkthisway/urls.py
from django.contrib import admin
from django.urls import path, include
from walkthisway.views import Index
from orders.views import my_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('', include('users.urls',namespace='users')),
    path('', include('customers.urls', namespace='customers')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('stripe/webhook/', my_webhook, name='stripe_webhook')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

src/orders/models.py
from django.db import models
from django.utils import timezone

from customers.models import Customer
from products.models import Product

# Create your models here.
class Order(models.Model):
    customer = models.ForeignKey(Customer, models.CASCADE, related_name='orders')
    closed = models.BooleanField('Closed', default=False)
    shipped = models.BooleanField('Shipped', default=False)
    date_ordered = models.DateField('Date Ordered', default=timezone.now)

    @property
    def get_total_items(self) -> int:
        total = sum([item.quantity for item in self.items.all()])
        return total
    
    @property
    def get_total(self):
        total = 0
        for item in self.items.all():
            total += item.quantity * item.product.price
        
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, models.CASCADE, related_name='order_items')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    quantity = models.IntegerField('Quantity', default=0)

    @property
    def get_total(self):
        return self.product.price * self.quantity


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, related_name='addresses', null=True, blank=True)
    order = models.ForeignKey('orders.Order', on_delete=models.CASCADE, related_name='address', null=True, blank=True)
    zip_code = models.CharField('Zip Code', max_length=20)
    city = models.CharField('City', max_length=255)
    state = models.CharField('State', max_length=255)
    address_line1 = models.CharField('Address Line 1', max_length=500)
    address_line2 = models.CharField('Address Line 2', max_length=500)

src/orders/forms.py
from django import forms
from orders.models import ShippingAddress

class ShippingForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = (
            'address_line1', 'address_line2', 'city',
            'state', 'zip_code'
            )
        
        widgets = {
            'address_line1': forms.TextInput(attrs={'class': 'form-control'}),
            'address_line2': forms.TextInput(attrs={'class':'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.TextInput(attrs={'class': 'form-control'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control'})
        }

src/orders/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from django.urls import reverse
import json
import stripe

from products.models import Product
from orders.models import Order, OrderItem, ShippingAddress
from orders.forms import ShippingForm
from orders.utils import get_cart_data

from datetime import date

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
class AddProductView(generic.View):
    def post(self, request, *args, **kwargs):

        data = json.loads(request.body)

        customer = request.user.customer
        product = Product.objects.get(pk=data['productId'])

        if product.quantity >= 1:
            order, created = Order.objects.get_or_create(customer=customer,closed=False)
            orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)
            orderitem.quantity = orderitem.quantity + 1
            orderitem.save()

            return JsonResponse('Item Added', safe=False)

        return JsonResponse('Item Failed to add!', safe=False)


class UpdateOrderItemView(generic.View):
    def post(self, request, *args, **kwargs):

        data = json.loads(request.body)

        action = data['action']
        customer = request.user.customer
        product = Product.objects.get(pk=data['productId'])

        order, created = Order.objects.get_or_create(customer=customer,closed=False)
        orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)


        if action == 'add':
            if product.quantity >= 1 and product.quantity >= orderitem.quantity + 1:
                print('adding')
                orderitem.quantity += 1

        elif action == 'remove':
            if orderitem.quantity > 0:
                orderitem.quantity -= 1

        orderitem.save()

        if orderitem.quantity == 0:
            orderitem.delete()

        return JsonResponse('Item Updated!', safe=False)


class OrderDetailView(generic.DetailView):
    template_name = 'order_detail.html'
    model = Order
    context_object_name = 'order'


class CartView(generic.View):
    template_name = 'cart.html'
    def get(self, request, *args, **kwargs):
        context = {}
        # customer = request.user.customer
        # order, _ = Order.objects.get_or_create(customer=customer, closed=False)

        cart = get_cart_data(self.request)

        context['order'] = cart['order']
        context['items'] = cart['items']
        context['cart_items'] = cart['cart_items']


        return render(request, self.template_name, context)
    

class CheckoutView(generic.View):
    template_name = 'checkout.html'
    form_class = ShippingForm


    def get(self, request, *args, **kwargs):
        context = {}
        form = self.form_class()
        # customer = request.user.customer
        # order = Order.objects.filter(customer=customer, closed=False).first()

        cart = get_cart_data(request)

        context['order'] = cart['order']
        context['items'] = cart['items']

        # context['order'] = order
        context['address_form'] = form
        return render(request, self.template_name, context)
    
    
    def post(self, request, *args, **kwargs):
        context = {}

        form = self.form_class(request.POST)
        
        if form.is_valid():
            shipping_address: ShippingAddress = form.save(commit=False)
            customer = request.user.customer
            order = Order.objects.filter(customer=customer, closed=False).first()

            shipping_address.customer = customer
            shipping_address.order = order
            
            checkout_session = stripe.checkout.Session.create(
                line_items=[
                    {
                        'price_data': {
                            'currency':'mxn',
                            'unit_amount': str(int(order.get_total*100)),
                            'product_data': {
                                'name': 'Orden'
                            }
                        },
                        'quantity': str(order.get_total_items),
                    }
                ],
                customer_email=customer.user.email,
                mode='payment',
                success_url = settings.SITE_URL + reverse('orders:success'),
                cancel_url = settings.SITE_URL + reverse('orders:cart'),
                metadata={'order_pk': order.pk, 'customer_pk': customer.pk}
            )

            return redirect(checkout_session.url)
        
        context['form'] = form

        return render(request, self.template_name, context=context)


class SuccessView(generic.TemplateView):
    template_name = 'success.html'


# Stripe Fullfillment
@csrf_exempt
def my_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.ENDPOINT_SECRET
        )
    except ValueError as e:
        print(e)
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        print(e)
        return HttpResponse(status=400)
    
    if event['type'] == 'checkout.session.completed':
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items']
        )

        order = Order.objects.get(pk=session.metadata.order_pk)

        for item in order.items.all():
            item.product.quantity -= item.quantity
            item.product.save()

        order.closed = True
        order.date_ordered = date.today()
        order.save()


    return HttpResponse(status=200)

src/orders/templates/cart.html
{% extends 'base.html' %}

{% block body %}

    <div>
    <!-- <div style="margin-left: 25%; margin-right: 25%;"> -->
        <h2>Cart</h2>
        <hr>

        <table class="table table-hover">
            <thead class="text-center">
                <tr>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th>Quantity</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="text-center align-middle">
                {% for item in items %}
                    <tr>
                        <td>
                            <a href="{% url 'products:product_detail' slug=item.product.slug %}" style="text-decoration: none;">
                                <img src="{{ item.product.imageURL }}" alt="{{ item.product.name }}" height="100" width="150">
                                {{ item.product.name }}
                            </a>
                        </td>
                        <td>
                            {{ item.product.price }}
                        </td>
                        <td>
                            {{ item.get_total }}
                        </td>
                        <td>
                            <div>
                                <button class="update-cart btn btn-sm btn-outline-primary" data-action="add" data-product="{{ item.product.pk }}"><i class="fa-solid fa-caret-up"></i></button>
                            </div>
                            <div class="fs-4">
                                {{ item.quantity }}
                            </div>
                            <div>
                                <button class="update-cart btn btn-sm btn-outline-primary" data-action="remove" data-product="{{ item.product.pk }}"><i class="fa-solid fa-caret-down"></i></button>
                            </div>
                        </td>
                        <td>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex align-items-center">
            <div>
                Items: {{ cart_items }} <br>
                Total: {{ order.get_total }}
            </div>
            <a class="btn btn-primary ms-auto" href="{% url 'orders:checkout' %}">Go to Checkout</a>
        </div>
    </div>

    <script>
        let updateBtns = document.getElementsByClassName('update-cart');

       for (let i = 0; i < updateBtns.length; i++){
        updateBtns[i].addEventListener('click', function(){
            let productId = this.dataset.product;
            let action = this.dataset.action;
            // console.log(productId)
            item = {
                pk: productId
            }

            if (user == 'AnonymousUser'){
                // console.log(productId)
                addCookieItem(item, action)
            }else{
                updateUserOrder(item, action)

            }


            // fetch("{% url 'orders:update_orderitem' %}",{
            //     headers:{
            //         'Content-Type': 'application/json',
            //         'X-CSRFToken': '{{ csrf_token }}'
            //     },
            //     body: JSON.stringify({productId, action}),
            //     method: 'POST'
            // }).then(response=>{
            //     return response.json()
            // }).then(data=>{
            //     console.log(data)   
            //     location.reload()
            // })
        });
       }

       // Add to Cookie Cart
       function addCookieItem(product, action){
            console.log(product)
            if(action == 'add'){
                if(!cart[product.pk]){
                    cart[product.pk] = {'quantity': 1};
                }else{
                    cart[product.pk]['quantity'] += 1;
                }
            }
            
            if(action == 'remove'){
                cart[product.pk]['quantity'] -= 1;

                if(cart[product.pk]['quantity'] <= 0){
                    delete cart[product.pk];
                }
            }

            document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/';
            location.reload();
        }


        // Update Log In User
        function updateUserOrder(product, action){
            let url = "{% url 'orders:update_orderitem' %}";

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                body: JSON.stringify({
                    'productId': product.pk,
                    'action': action
                }),
            }).then(response=>{
                return response.json()
            }).then(data=>{
                location.reload()
            });
        }

    </script>
{% endblock %}

src/orders/templates/checkout.html
{% extends 'base.html' %}

{% block body %}
    <div>
        <h2>Checkout</h2>
        <div class="row">
            <div class="col-md-8">
                <div class="bg-light p-3 shadow rounded">
                    <h4>Shipping Info</h4>
                    <hr>
                    <form method="post">
                        {% csrf_token %}
                        {{ address_form.as_p }}
                        
                        <div class="d-flex">
                            <input type="submit" class="ms-auto btn btn-primary" value="pay now">
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-4">
                <div>
                    <h4>Recap</h4>
                    <hr>
                    <table class="table table-hover">
                        <caption>Total: {{ order.get_total }} $</caption>
                        <thead class="table-dark">
                            <tr>
                                <th>Item</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in items %}
                                <tr>
                                    <td>{{ item.product.name }}</td>
                                    <td>{{ item.product.price }}</td>
                                    <td>{{ item.quantity }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>


            </div>

        </div>
    </div>

{% endblock %}                                                                                                               

src/orders/templates/order_detail.html
{% extends 'base.html' %}

{% block body %}

    <div class="bg-light rounded shadow p-3 mb-3">
        <h4>Order Info</h4>
        <hr>
        <p class="text-center">
            <strong>Date Ordered</strong> {{ order.date_ordered }} <br>
            <strong>Shipped: </strong> {% if order.shipped %} Yes {% else %} No {% endif %} <br>
            <strong>Delivered: </strong> No <br>
        </p>
    </div>

    <h4>Items</h4>
    <table class="table table-hover">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th>Item</th>
                <th>Price</th>
                <th>Total Price</th>
                <th>Quantity</th>
            </tr>
        </thead>

        <tbody>
            {% for item in order.items.all %}
                <tr>
                    <td scope="col">{{ forloop.counter }}</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.get_total }}</td>
                    <td>{{ item.quantity }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/orders/templates/success.html
{% extends 'base.html' %}

{% block body %}

    <h1>Thank You For Purchasing</h1>
    <p>Your order is being process, you should receive an email with the confirmation!</p>

{% endblock %}