src/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('add-product/', views.AddProductView.as_view(), name='add_product'),
    path('upate-orderitem/', views.UpdateOrderItemView.as_view(), name='update_orderitem'),
    path('order-detail/<int:pk>/',  views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('success/', views.SuccessView.as_view(), name='success'),

]

src/products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('register/', views.ProductCreateView.as_view(), name='product_create'),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('<slug:slug>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('<slug:slug>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
]

src/users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

src/walkthisway/urls.py
from django.contrib import admin
from django.urls import path, include
from walkthisway.views import Index
from orders.views import my_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('', include('users.urls',namespace='users')),
    path('', include('customers.urls', namespace='customers')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('stripe/webhook/', my_webhook, name='stripe_webhook')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

src/products/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

from pathlib import Path
from PIL import Image

def image_upload_handler(instance, filename) -> str:
    result = 'products'
    extension = Path(filename).suffix
    result = Path(result, instance.name + extension)
    return str(result)

class Product(models.Model):
    name = models.CharField('Name', max_length=255, unique=True)
    slug = models.SlugField('Slug', max_length=255, unique=True)
    description = models.TextField('Description')
    price = models.DecimalField('Price', max_digits=8, decimal_places=2)
    image = models.ImageField('Image', upload_to=image_upload_handler)
    quantity = models.IntegerField('Quantity', default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        
        if Path(self.image.path).exists():
            img = Image.open(self.image.path)
            if img.height > 500 or img.width > 500:
                img.thumbnail((500, 500))
                img.save(self.image.path)
        
        super().save(*args, **kwargs)
        
        
    def delete(self, *args, **kwargs):
        img_path = Path(self.image.path)
        if img_path.exists():
            img_path.unlink()

        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'slug': self.slug})
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self) -> str:
        return f'{self.name}'
    

    def __repr__(self) -> str:
        return f'<Product> {self.__str__}'
    

src/products/forms.py
from django import forms

from products.models import Product

class ProductRegisterForm(forms.ModelForm):
    price = forms.DecimalField(min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    quantity = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    
    class Meta:
        
        model = Product
        fields = (
            'name', 'description', 'price', 'image', 'quantity'
        )
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'})
        }

    field_order = [
        'name', 'price', 'quantity',
        'description','image'
    ]

src/products/views.py
from django.shortcuts import render, redirect
from django.views import generic

from products.models import Product
from products.forms import ProductRegisterForm

template_prefix = 'products/'

class ProductListView(generic.ListView):
    template_name = template_prefix + 'product_list.html'
    model = Product
    context_object_name = 'products'


class ProductDetailView(generic.DetailView):
    template_name = template_prefix + 'product_detail.html'
    model = Product
    context_object_name = 'product'


class ProductCreateView(generic.CreateView):
    template_name = template_prefix + 'product_create.html'
    model = Product
    form_class = ProductRegisterForm


class ProductUpdateView(generic.UpdateView):
    template_name = template_prefix + 'product_update.html'
    model = Product
    form_class = ProductRegisterForm
    context_object_name = 'product'


class ProductDeleteView(generic.DeleteView):
    template_name = template_prefix + 'product_delete.html'
    model = Product

src/products/templates/products/product_create.html
{% extends 'base.html' %}

{% block body %}

    <h1>Add a New Product</h1>
    <hr>

    <form method="post" enctype="multipart/form-data" style="margin-left: 20%; margin-right: 20%;" class="shadow rounded p-3 border">
        {% csrf_token %}

        <div id="step-1">
            <label for="" class="form-label">{{ form.name.label}}</label>
            <div>
                <div id="name-errors"></div>
                <div id="name-server-errors">
                    {% for error in form.name.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>

                {{ form.name }}
            </div>
        </div>

        <div id="step-2" style="display: none;">
            <label for="" class="form-label">{{ form.price.label }}</label>
            <div>
                <div id="price-errors"></div>
                <div id="price-server-errors">
                    {% for error in form.price.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {{ form.price }}
            </div>
            <label for="" class="form-label">{{ form.quantity.label }}</label>
            <div>
                <div id="quantity-errors"></div>
                <div id="quantity-server-errors">
                    {% for error in form.quantity.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {{ form.quantity }}
            </div>
        </div>

        <div id="step-3" style="display: none;">
            <label for="" class="form-label">{{ form.description.label }}</label>
            <div>
                <div id="desc-errors"></div>
                <div id="desc-server-errors">
                    {% for error in form.description.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {{ form.description }}
            </div>
        </div>

        <div id="step-4" style="display: none;">
            <label for="" class="form-label">{{ form.image.label }}</label>
            <div>
                <div id="image-server-errors">
                    {% for error in form.image.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {{ form.image }}
            </div>
        </div>



        <div class="d-flex mt-3">
            <button class="me-auto btn btn-outline-primary" type="button" id="backBtn" style="display: none;">Back</button>
            <a href="{% url 'products:product_list' %}" class="btn btn-outline-warning me-auto" id="cancelBtn">Cancel</a>
            <button class="ms-auto btn btn-outline-primary" type="button" id="nextBtn">Next</button>
            <input type="submit" class="btn btn-outline-primary ms-auto" value="Add" id="submitBtn" style="display: none;">
        </div>


    <script>
        let step = 1;

        let step1Div = document.getElementById('step-1');
        let step2Div = document.getElementById('step-2');
        let step3Div = document.getElementById('step-3');
        let step4Div = document.getElementById('step-4');
        
        let nextBtn = document.getElementById('nextBtn');
        let backBtn = document.getElementById('backBtn');
        let cancelBtn = document.getElementById('cancelBtn');
        let submitBtn = document.getElementById('submitBtn');

        let nameInputId = '{{ form.name.auto_id }}'
        let quantityInputId = '{{ form.quantity.auto_id }}';
        let priceInputId = '{{ form.price.auto_id }}';
        let descInputId = '{{ form.description.auto_id }}';
        
        let nameServerErrors = document.getElementById('name-server-errors');
        let priceServerErrors = document.getElementById('price-server-errors');
        let quantityServerErrors = document.getElementById('quantity-server-errors');
        let descServerErrors = document.getElementById('desc-server-errors');
        let imageServerErrors = document.getElementById('image-server-errors');


        let makeStepVisible = (step) =>{
            switch (step) {
                case 1:
                    step1Div.style.display = 'block';
                    step2Div.style.display = 'none';
                    step3Div.style.display = 'none';
                    step4Div.style.display = 'none';

                    cancelBtn.style.display = 'inline-block';
                    backBtn.style.display = 'none'
                    // makeStepVisible(step1Div, [step2Div, step3Div, step4Div]);
                    break;
                case 2:
                    step1Div.style.display = 'none';
                    step2Div.style.display = 'block';
                    step3Div.style.display = 'none';
                    step4Div.style.display = 'none';

                    cancelBtn.style.display = 'none';
                    backBtn.style.display = 'inline-block'
                    break;
                case 3:
                    step1Div.style.display = 'none';
                    step2Div.style.display = 'none';
                    step3Div.style.display = 'block';
                    step4Div.style.display = 'none';

                    nextBtn.style.display = 'inline-block';
                    submitBtn.style.display = 'none';
                    break;
                case 4:
                    step1Div.style.display = 'none';
                    step2Div.style.display = 'none';
                    step3Div.style.display = 'none';
                    step4Div.style.display = 'block';

                    nextBtn.style.display = 'none';
                    submitBtn.style.display = 'inline-block'
                    break;

            }
        };

        let validateInputs = step =>{

            let nameInput = document.getElementById(nameInputId);
            let nameErrorDiv = document.getElementById('name-errors');
            
            let priceInput = document.getElementById(priceInputId)
            let priceErrorDiv = document.getElementById('price-errors');

            let quantityInput = document.getElementById(quantityInputId);
            let quantityErrorDiv = document.getElementById('quantity-errors');

            let descInput = document.getElementById(descInputId);
            let descErrorDiv = document.getElementById('desc-errors');

            switch (step) {
                case 2:
                    let name = String(nameInput.value)
                    if (nameErrorDiv.lastChild !== null) nameErrorDiv.removeChild(nameErrorDiv.lastChild)

                    if (name === '' || name.length > 255){
                        let nameErrorMessageText = '';
                        let nameErrorMessage = document.createElement('div');
                        nameErrorMessage.classList.add('alert','alert-danger');

                        if (name == '') nameErrorMessageText = 'Name Must not be Empty!'
                        else if (name.length > 255) nameErrorMessageText = 'Name must be 255 characters or less'
                            
                        nameErrorMessage.innerText = nameErrorMessageText

                        nameErrorDiv.appendChild(nameErrorMessage)
                        nameInput.focus()
                        return false
                    }
                    break;
                
                case 3:
                    let quantity = (quantityInput.value !== '') ? Number(quantityInput.value): '';
                    let price = (priceInput.value !== '') ? Number(priceInput.value) : '';

                    if (priceErrorDiv.lastChild !== null) priceErrorDiv.removeChild(priceErrorDiv.lastChild);
                    if (quantityErrorDiv.lastChild !== null) quantityErrorDiv.removeChild(quantityErrorDiv.lastChild);
                    
                    // if(price === '' || price < 0){
                    if(price === ''){
                        let priceErrorMessageText = '';
                        let priceErrorMessage = document.createElement('div');
                        priceErrorMessage.classList.add('alert','alert-danger');

                        if (price === '') priceErrorMessageText = 'Price Must not be Empty!';
                        // else if (price < 0) priceErrorMessageText = 'Price must be greater than 0!';

                        priceErrorMessage.innerText = priceErrorMessageText;

                        priceErrorDiv.appendChild(priceErrorMessage);
                        priceInput.focus()
                        return false
                    }

                    if (quantity === '' || quantity < 0){
                        let quantityErrorMessageText = '';
                        let quantityErrorMessage = document.createElement('div');
                        quantityErrorMessage.classList.add('alert','alert-danger');

                        if(quantity === '') quantityErrorMessageText = 'Quantity Must not be empty';
                        else if(quantity < 0) quantityErrorMessageText = 'Quantity must be greater than 0!';

                        quantityErrorMessage.innerText = quantityErrorMessageText;
                    
                        quantityErrorDiv.appendChild(quantityErrorMessage)
                        quantityInput.focus();
                        return false
                    }
                    break;
                case 4:
                    let description = String(descInput.value);

                    if (descErrorDiv.lastChild !== null) descErrorDiv.removeChild(descErrorDiv.lastChild);

                    if (description === ''){
                        let descErrorMessageText = '';
                        let descErrorMessage = document.createElement('div');
                        descErrorMessage.classList.add('alert','alert-danger');

                        if (description === '') descErrorMessageText = 'Description Must not be Empty!';

                        descErrorMessage.innerText = descErrorMessageText;

                        descErrorDiv.appendChild(descErrorMessage)
                        descInput.focus();
                        return false;
                    }
                    break;
            }

            return true;
        }

        // Check for server errors
        function checkServerErrors(){
            if (nameServerErrors.innerText.trim() !== ''){
                step = 1;
                makeStepVisible(1)
                return;
            }

            if (priceServerErrors.innerText.trim() !== '' || quantityServerErrors.innerText.trim() !== ''){
                step = 2;
                makeStepVisible(2);
                return;
            }

            if (descServerErrors.innerText.trim() !== ''){
                step = 3;
                makeStepVisible(3);
                return
            }

            if (imageServerErrors.innerText.trim() !== ''){
                step = 4;
                makeStepVisible(4)
                return
            }

            step = 1;
            makeStepVisible(1)
        }

        checkServerErrors()

        nextBtn.addEventListener('click', event=>{
            step = (step < 4) ? step + 1 : 4;

            let isValid = validateInputs(step);

            if (!isValid){
                step = step - 1;
                return
            }
            makeStepVisible(step)
        })

        backBtn.addEventListener('click', event=>{
            step = (step > 1) ? step - 1: 1;
            makeStepVisible(step)
        })


    </script>

{% endblock %}

src/products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block body %}
    <h1>Do you wish to remove Product {{ product.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <a href="{% url 'products:product_detail' slug=product.slug %}">Cancel</a>
        <input type="submit" value="Delete">
    </form>

{% endblock %}

src/products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block body %}


        <h1>{{ product.name }}</h1>
        
        <div class="row mt-3">
            <div class="col-md-5">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" height="200" style="width: 75%;" class="rounded">
            </div>

            <div class="col-md-7">
                <div class="shadow rounded p-2 mb-3 bg-body-secondary">
                    <h5>Details</h5>
                    <p>
                        {{ product.description }}
                    </p>
                </div>

                <table class="table mb-3">
                    <tr>
                        <td>Name:</td>
                        <td>{{ product.name }}</td>
                    </tr>
                    <tr>
                        <td>Price:</td>
                        <td>{{ product.price }}</td>
                    </tr>
                    <tr>
                        <td>Available:</td>
                        <td>{{ product.quantity }}</td>
                    </tr>
                </table>

                <button class="btn btn-lg btn-primary" style="width: 100%;" type="button" id="addBtn">Add To Cart</button>
            </div>
        </div>


        <script>
            let addBtn = document.getElementById('addBtn');

            let addFunction = (event) =>{

                const item = {
                    pk: '{{ product.id }}',
                    price: '{{ product.price }}',
                    slug: '{{ product.slug }}',
                    name: '{{ product.name }}',
                    imageURL: '{{ product.imageURL }}'
                }

                if (user == 'AnonymousUser'){
                    addCookieItem(item, 'add');
                }else{
                    updateUserOrder(item, 'add')
                }

                // fetch("{% url 'orders:update_orderitem' %}",{
                //     headers: {
                //         'Content-Type': 'application/json',
                //         'X-CSRFToken': '{{ csrf_token }}'
                //     },
                //     method: 'POST',
                //     body: JSON.stringify({
                //         'productId': '{{ product.id }}',
                //         'action': 'add'
                //     })
                // }).then(response=>{
                //     return response.json()
                // }).then(data=>{
                //     console.log('data',data)
                //     location.reload()
                // })
            }

            addBtn.addEventListener('click', addFunction)


            // Add to Cookie Cart
            function addCookieItem(product, action){
                
                if(action == 'add'){
                    if(!cart[product.pk]){
                        cart[product.pk] = {'quantity': 1};
                    }else{
                        cart[product.pk]['quantity'] += 1;
                    }
                    cart[product.pk]['product'] = product
                }
                
                if(action == 'remove'){
                    cart[product.pk]['quantity'] -= 1;

                    if(cart[product.pk]['quantity'] <= 0){
                        delete cart[product.pk];
                    }
                }

                document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/';
                location.reload();
            }

            // Update Log In User
            function updateUserOrder(product, action){
                let url = "{% url 'orders:update_orderitem' %}";

                fetch(url, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: JSON.stringify({
                        'productId': product.pk,
                        'action': action
                    }),
                }).then(response=>{
                    return response.json()
                }).then(data=>{
                    location.reload()
                });
            }



        </script>

{% endblock %}

src/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block body %}

        <h2>Products</h2>
        <a href="{% url 'products:product_create' %}">Add Product</a>
        <hr>


        <div class="row">
            {% for product in products %}
            <div class="col-md-4">
                <div class="card" style="width: 14rem;">
                    <div class="p-2">
                        <a href="{% url 'products:product_detail' slug=product.slug %}">
                            <img src="{{ product.image.url }}" alt="{{ product.name}}" class="card-img-top" height="110">
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'products:product_detail' slug=product.slug %}">{{ product.name }}</a></h5>
                        <p class="card-text">
                            {{ product.price }}$
                        </p>
                        <a href="{% url 'products:product_detail' slug=product.slug %}" class="btn btn-sm btn-primary">Buy Now</a>
                    </div>
                </div>
            </div>
                
            {% empty %}
            <h5>No Products Found!</h5>
            {% endfor %}
        </div>



{% endblock %}

src/products/templates/products/product_update.html
{% extends 'base.html' %}

{% block body %}

    <h1>{{ product.name }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'products:product_detail' slug=product.slug %}">Cancel</a>
        <input type="submit" value="Save">
    </form>

{% endblock %}